# Generated by Django 3.0.dev20190330204916 on 2019-04-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_family_subfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subFamily',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.SubFamily'),
        ),
    ]
